require '../modules/todo.module.coffee'
require '../config/index.config.coffee'
require '../factories/indexFactory.coffee'
require '../controllers/indexCtrl.coffee'
require '../directives/indexDirective.coffee'